In [1]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}


In [2]:
df = pd.DataFrame(data)
df

calories  duration
0       420        50
1       380        40
2       390        45

In [3]:
df.loc[0]

calories    420
duration     50
Name: 0, dtype: int64

In [4]:
df.loc[[0, 1]]

calories  duration
0       420        50
1       380        40

In [6]:
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
df

calories  duration
day1       420        50
day2       380        40
day3       390        45

In [ ]:
pd.read_csv('filename.csv')
pd.read_json('data.json')

df.head(10)
df.tail()
df.info()
df.isnull().sum()

In [ ]:
df.dropna()

df.dropna(inplace=True)
#dropna(inplace = True) will NOT return a new DataFrame, but it will remove all rows containing NULL values from the original DataFrame.

mean,median , mode ,ffill,bfill

df['Date'] = pd.to_datetime(df['Date'])

#Remove rows with a NULL value in the "Date" column
df.dropna(subset=['Date'], inplace = True)



In [7]:
df

calories  duration
day1       420        50
day2       380        40
day3       390        45

In [8]:
df.loc['day1', 'calories'] = 450
df

calories  duration
day1       450        50
day2       380        40
day3       390        45

In [9]:
df.drop_duplicates(inplace = True)

In [11]:
df.corr()

calories  duration
calories  1.000000  0.924473
duration  0.924473  1.000000

In [12]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('train.csv')
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [15]:
df.shape

(550068, 12)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  object 
 3   Age                         550068 non-null  object 
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB


In [17]:
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [18]:
# fill the missing value

df['Product_Category_2'].fillna(df['Product_Category_2'].mean(),inplace=True)
df['Product_Category_3'].fillna(df['Product_Category_3'].mean(),inplace=True)

In [19]:
df.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [21]:
#Product_Category_2,Product_Category_3 need to see the head

df[['Product_Category_2', 'Product_Category_3']].head()

Product_Category_2  Product_Category_3
0            9.842329           12.668243
1            6.000000           14.000000
2            9.842329           12.668243
3           14.000000           12.668243
4            9.842329           12.668243

In [22]:
# make a copy

df1 = df.copy()
df1.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0            9.842329           12.668243      8370  
1            6.000000           14.000000     15200  
2            9.842329           12.668243      1422  
3           14.000000           12.668243      1057  
4            9.842329           12.668243      7969

In [23]:
# select first row of dataframe

df1.loc[0]

User_ID                         1000001
Product_ID                    P00069042
Gender                                F
Age                                0-17
Occupation                           10
City_Category                         A
Stay_In_Current_City_Years            2
Marital_Status                        0
Product_Category_1                    3
Product_Category_2             9.842329
Product_Category_3            12.668243
Purchase                           8370
Name: 0, dtype: object

In [24]:
# select the first 5 rows in Purchase column

df1.loc[:,'Purchase'].head()

0     8370
1    15200
2     1422
3     1057
4     7969
Name: Purchase, dtype: int64

In [25]:
# get index of first occurance of maximum Purchase value

df1['Purchase'].idxmax()

87440

In [27]:
# get the row with maximum purchase value

df1.loc[df1['Purchase'].idxmax()]

User_ID                         1001474
Product_ID                    P00052842
Gender                                M
Age                               26-35
Occupation                            4
City_Category                         A
Stay_In_Current_City_Years            2
Marital_Status                        1
Product_Category_1                   10
Product_Category_2                 15.0
Product_Category_3            12.668243
Purchase                          23961
Name: 87440, dtype: object

In [26]:
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [28]:
# Product_Category_1 sort this column
df.sort_values(by=['Product_Category_1'])


User_ID Product_ID Gender    Age  Occupation City_Category  \
271814  1005880  P00016042      M  26-35           1             A   
208659  1002109  P00298942      M  26-35          16             B   
436707  1001231  P00334242      M  26-35          12             C   
108508  1004685  P00025442      M  36-45           1             B   
208658  1002109  P00062842      M  26-35          16             B   
...         ...        ...    ...    ...         ...           ...   
547638  1002549  P00375436      M    55+          13             C   
547640  1002553  P00375436      M  26-35           7             C   
547642  1002556  P00371644      M  26-35           4             C   
547644  1002558  P00375436      M    55+          17             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
271814                          1               1                   1   
208659                          2               0                   1   
436707                          1               0                   1   
108508                          2               1                   1   
208658                          2               0                   1   
...                           ...             ...                 ...   
547638                          3               1                  20   
547640                          0               0                  20   
547642                          2               0                  20   
547644                          3               1                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
271814           16.000000           12.668243      8322  
208659            5.000000           12.668243      7823  
436707            8.000000           12.668243     15803  
108508            2.000000            9.000000     15647  
208658            2.000000           13.000000     11643  
...                    ...                 ...       ...  
547638            9.842329           12.668243       613  
547640            9.842329           12.668243       240  
547642            9.842329           12.668243       120  
547644            9.842329           12.668243       373  
550067            9.842329           12.668243       490  

[550068 rows x 12 columns]

In [29]:
# #Gender
# count     550068
# unique         2
# top            M
# freq      414259
# Name: Gender, dtype: object


df['Gender'].describe()

count     550068
unique         2
top            M
freq      414259
Name: Gender, dtype: object

In [30]:
df['Gender'].value_counts()

M    414259
F    135809
Name: Gender, dtype: int64

In [31]:
# unique age
df['Age'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [32]:
df['Age'].nunique()

7

In [33]:
df = pd.DataFrame({'ID': {0: 23, 1: 43, 2: 12,  
                          3: 13, 4: 67, 5: 89, 
                          6: 90, 7: 56, 8: 34}, 
                     
                 'Name': {0: 'Ram', 1: 'Deep', 2: 'Yash', 
                          3: 'Aman', 4: 'Arjun', 5: 'Aditya', 
                          6: 'Akash', 7: 'Chalsea', 
                          8: 'Divya'}, 
                     
                 'Marks': {0: 89, 1: 97, 2: 45, 
                           3: 78, 4: 56, 5: 76, 
                           6: 81, 7: 87, 8: 100}, 
                     
                 'Grade': {0: 'B', 1: 'A', 2: 'F', 
                           3: 'C', 4: 'E', 5: 'C', 
                           6: 'B', 7: 'B', 8: 'A'}}) 


df



ID     Name  Marks Grade
0  23      Ram     89     B
1  43     Deep     97     A
2  12     Yash     45     F
3  13     Aman     78     C
4  67    Arjun     56     E
5  89   Aditya     76     C
6  90    Akash     81     B
7  56  Chalsea     87     B
8  34    Divya    100     A

In [34]:
#aggregate function on marks (mean)

pd.pivot_table(df,index = ['Grade'],
                 values = ['Marks'],
                aggfunc = np.mean)

Marks
Grade           
A      98.500000
B      85.666667
C      77.000000
E      56.000000
F      45.000000

In [35]:
df = pd.DataFrame({'A': ['John', 'Boby', 'Mina', 'Peter', 'Nicky'], 
      'B': ['Masters', 'Graduate', 'Graduate', 'Masters', 'Graduate'], 
      'C': [27, 23, 21, 23, 24]}) 
   
df 

A         B   C
0   John   Masters  27
1   Boby  Graduate  23
2   Mina  Graduate  21
3  Peter   Masters  23
4  Nicky  Graduate  24

In [36]:
table = pd.pivot_table(df,index=['A','B'])
table

C
A     B           
Boby  Graduate  23
John  Masters   27
Mina  Graduate  21
Nicky Graduate  24
Peter Masters   23

In [37]:
data = {
    'day': ['day1', 'day2', 'day1', 'day3', 'day2', 'day3'],
    'calories': [420, 380, 450, 390, 370, 400],
    'duration': [50, 40, 60, 45, 35, 50]
}

df = pd.DataFrame(data)

In [38]:
pivot_table = pd.pivot_table(df, 
                             values=['calories', 'duration'], 
                             index='day', 
                             aggfunc={'calories': 'sum', 'duration': 'mean'})
pivot_table

calories  duration
day                     
day1       870      55.0
day2       750      37.5
day3       790      47.5

In [40]:
d_string = "2023-09-17 14:30:00"

In [41]:
d_date = pd.to_datetime(d_string)
d_date

Timestamp('2023-09-17 14:30:00')

In [ ]:
# Mean works best when you have a normally distributed dataset with no significant outliers.
# Median is better for skewed data or when dealing with outliers.
# Mode is ideal for categorical data or when one value occurs most often and is a good replacement for missing values.

In [42]:
data = {
    'Name': ['John', 'Emily', 'Alex', 'Sarah', 'Jack'],
    'Age': [25, 30, 35, 40, 45],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male']
}
df = pd.DataFrame(data)
df

Name  Age  Gender
0   John   25    Male
1  Emily   30  Female
2   Alex   35    Male
3  Sarah   40  Female
4   Jack   45    Male

In [43]:
# index as name columns

df1= df.set_index('Name')
df1

Age  Gender
Name              
John    25    Male
Emily   30  Female
Alex    35    Male
Sarah   40  Female
Jack    45    Male

In [ ]:
loc and iloc difference

loc -- label based in dexing, row and column labels such as index names or column names

df.loc['day1', 'calories'] 
df.loc[['day1', 'day2'], ['calories', 'duration']]

iloc(integer based indexing)

-- Used for: Accessing data based on integer positions 
-- Works with row and column positions     
    
    df.iloc[0, 0]
    
    
    
Use .loc[] when you want to access data based on labels (such as named indices or column headers).
Use .iloc[] when you want to access data based on integer positions.

In [47]:
# First DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})

# Second DataFrame
df2 = pd.DataFrame({
    'ID': [3, 4, 5, 6],
    'Salary': [70000, 80000, 60000, 65000]
})

In [48]:
df1

ID     Name  Age
0   1    Alice   24
1   2      Bob   27
2   3  Charlie   22
3   4    David   32

In [49]:
df2

ID  Salary
0   3   70000
1   4   80000
2   5   60000
3   6   65000

In [50]:
merged_inner = pd.merge(df1, df2, on='ID', how='inner')
merged_inner

ID     Name  Age  Salary
0   3  Charlie   22   70000
1   4    David   32   80000

In [51]:
merged_left = pd.merge(df1, df2, on='ID', how='left')
merged_left

ID     Name  Age   Salary
0   1    Alice   24      NaN
1   2      Bob   27      NaN
2   3  Charlie   22  70000.0
3   4    David   32  80000.0

In [52]:
merged_right = pd.merge(df1, df2, on='ID', how='right')
merged_right

ID     Name   Age  Salary
0   3  Charlie  22.0   70000
1   4    David  32.0   80000
2   5      NaN   NaN   60000
3   6      NaN   NaN   65000

In [53]:
# generate random number from to 0 to 100

from numpy import random

x = random.randint(100)
print(x)

37


In [54]:
#5 random integers from 0 to 100

x=random.randint(100, size=(5))

print(x)

[44 64 80 50 14]


In [55]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

#Find the indexes where the value is 4

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [56]:
#Find the indexes where the values are even

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [57]:
arr = np.array([6, 7, 8, 9])

#Find the indexes where the value 7 should be inserted from right

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [58]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [60]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#Convert the following 1-D array with 12 elements into a 2-D array.

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [62]:
#Convert the following 1-D array with 12 elements into a 3-D array.

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [63]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [64]:
print(arr[2] + arr[3])

7


In [65]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

#Access the element on the first row, second column

print(arr[0,1])

2


In [66]:
#Access the element on the 2nd row, 5th column

arr[1, 4]

10